export const departments = {
  CSE: "Computer Science and Engineering",
  Design: "Design",
  HSS: "Humanities and Social Science",
  Physics: "Physics",
  Maths: "Mathematics",
  Chem: "Chemistry",
  DataScience: "Mehta School of Data Science",
  Mech: "Mechanical Engineering",
  EEE: "Electrical and Electronics Engineering",
  Civil: "Civil Engineering",
  Bio: "Bioscience and Bioengineering",
  Energy: "Energy Engineering",
  ChemEng: "Chemical Engineering",
};
