name: Deploy to AWS Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted # Using your GitHub self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Adjust based on your project

      - name: Install backend dependencies
        working-directory: server # Adjust based on your server path
        run: npm install

      - name: Start or Restart server with PM2
        working-directory: server # Adjust if needed
        run: |
          pm2 start src/index.js --name server || pm2 restart server
          pm2 save

      - name: Restart Nginx
        run: sudo systemctl restart nginx
