name: NodeJS with Webpack

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: |
          cd client
          npm install
          CI=false npm run build

      - name: Set GitHub user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push Build to `build` Branch
        run: |
          cd client
          git checkout -b build
          git add -f build
          git commit -m "Deploy: update build"
          git push origin build

  deploy:
    name: Deploy to AWS EC2
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout Build Branch
        uses: actions/checkout@v4
        with:
          ref: build

      - name: Deploy to AWS EC2
        run: |
          cd ~/Research_Intern_Portal
          git pull origin build
